nnn: update fzvim plugin

diff --git a/dot_config/nnn/plugins/executable_fzvim b/dot_config/nnn/plugins/executable_fzvim
--- a/dot_config/nnn/plugins/executable_fzvim
+++ b/dot_config/nnn/plugins/executable_fzvim
@@ -5,8 +5,10 @@
 #
 # Limitations: file names with ':' will break the script
 #
+# Dependencies: nvim/vim, fd,find, fzf/skim, rg, cut
+#
 # Shell: POSIX compliant
-
+# Author: @ram02z
 #
 # Options
 #
@@ -26,7 +28,7 @@ else
     exit 1
 fi
 
-# Supported file search utility
+# Supported file search utilities
 if [ "$(cmd_exists fd)" -eq "0" ]; then
     git_dirs=$(fd --type d -H -g '.git' --color=always --prune)
 elif [ "$(cmd_exists find)" -eq "0" ]; then
@@ -38,44 +40,85 @@ fi
 # Remove git suffix and check if only one directory exists
 if [ -n "$git_dirs" ]; then
     dirs=$(printf "%s" "$git_dirs" | rev | cut -d"/" -f2- | rev)
-    if [ $(printf "%s" "$git_dirs" | rg . -c) -eq "1" ]; then
+    if [ "$(printf "%s" "$git_dirs" | rg . -c)" -eq "1" ]; then
         [ "$dirs" != ".git" ] && cd "$dirs"
         unset dirs
     fi
 fi
 
-# Vim grep the directory
+# Check print_every_match option
 if [ "$print_every_match" -eq "0" ]; then
     RG_PREFIX="rg --column --no-heading --line-number --smart-case --color=ansi "
 else
     RG_PREFIX="rg --vimgrep --smart-case --color=ansi "
 fi
+
+# Vim grep the directory
 if [ "$(cmd_exists fzf)" -eq "0" ]; then
-    [ -n "$dirs" ] && cd $(printf "%s" "$dirs" | fzf --ansi)
+    [ -n "$dirs" ] && cd "$(printf "%s" "$dirs" | fzf --ansi)"
     sel=$(
     FZF_DEFAULT_COMMAND="$RG_PREFIX ''" \
-      fzf --bind "change:reload:$RG_PREFIX {q} || true" \
+      fzf -m --bind "change:reload:$RG_PREFIX {q} || true" \
           --ansi --phony --query ""
     )
 elif [ "$(cmd_exists sk)" -eq "0" ]; then
-    [ -n "$dirs" ] && cd $(printf "%s" "$dirs" | fzf --ansi)
-    sel=$(sk --ansi -i -c "$RG_PREFIX \"{}\"")
+    [ -n "$dirs" ] && cd "$(printf "%s" "$dirs" | sk --ansi)"
+    sel=$(sk --ansi -m -i -c "$RG_PREFIX \"{}\"")
 else
     exit 3
 fi
 
+
 if [ -n "$sel" ]; then
-    # Extract file name, line number, column number
-    fname=$(printf "%s" $sel | cut -f1 -d':')
-    lineno=$(printf "%s" $sel | cut -f2,2 -d':')
-    colno=$(printf "%s" $sel | cut -f2,3 -d':' | cut -f2 -d':')
+    IFS=
+    for line in $sel; do
+        # Extract file name, line number, column number
+        fname=$(printf "%s" "$line" | cut -f1 -d':')
+        lineno=$(printf "%s" "$line" | cut -f2,2 -d':')
+        colno=$(printf "%s" "$line"| cut -f2,3 -d':' | cut -f2 -d':')
+
+        # Check for picker mode
+        if [ "$3" ]; then
+            if [ "$fname" ]; then
+                if [ "-" = "$3" ]; then
+                    printf "%s\n" "$fname"
+                else
+                    printf "%s\n" "$fname" > "$3"
+                fi
+
+                # Tell `nnn` to clear its internal selection
+                printf "%s" "0p" > "$NNN_PIPE"
+            fi
+
+            exit 4
+        fi
+
+    done
+
+    # Get first file details
+    first=$(printf "%s" "$fname" | head -n 1)
+    lineno=$(printf "%s" "$lineno" | head -n 1)
+    colno=$(printf "%s" "$colno" | head -n 1)
 
     # Check if file can be opened
-    if [ "$fname" = "." ] || { ! [ -d "$fname" ] && ! [ -f "$fname" ]; }; then
-        printf "%s cannot be opened.\n" $fname
-        exit 4
+    if [ "$first" = "." ] || { ! [ -d "$first" ] && ! [ -f "$first" ]; }; then
+        printf "%s cannot be opened.\n" "$first"
+        exit 5
     fi
 
-    # Open file in editor
-    "$editor" "$fname" "+call cursor($lineno,$colno)"
+    # Get rest of files if selected
+    more_files=
+    last_line=""
+    IFS='
+    '
+    for line in $(printf "%s" "$fname" | tail -n +2); do
+       if [ "$line" != "$first" ] && [ "$last_line" != "$line" ]; then
+           more_files="$more_files$line "
+        fi
+        last_line="$line"
+    done
+    # Open file(s) in editor
+    # First selected file at exact pos
+    # Opens rest of files; TODO find out how to open multiple files at exact pos
+    "$editor" "$first" "+call cursor($lineno,$colno)" $more_files
 fi
